name: Automated PR Review by PullReviewX
on:
  pull_request:
    types: [opened]
jobs:
  review-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Copilot PR Review
        uses: kp9435-keril/pull-review-x@main
        with:
            GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}
            AZURE_OPENAI_APIKEY: ${{ secrets.AZURE_OPENAI_APIKEY }}
            AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
            AZURE_OPENAI_MODEL: "gpt-4o"
            PR_SUMMARY: True
            PR_SUGGEST_CHANGES: True
            PR_COMMENT_SUGGESTED_CHANGES: True
